// <auto-generated />
namespace CustomPermitWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Custom_permission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Custom_permission));
        
        string IMigrationMetadata.Id
        {
            get { return "201606241117512_Custom_permission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
