// <auto-generated />
namespace CustomPermitWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ministry_Permission_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ministry_Permission_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201605160147061_Ministry_Permission_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
