// <auto-generated />
namespace CustomPermitWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class decl_commodity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(decl_commodity));
        
        string IMigrationMetadata.Id
        {
            get { return "201606241028544_decl_commodity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
